# azure-pipeline.yml - Version avec Azure CLI
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Terraform avec Azure CLI'
  inputs:
    azureSubscription: 'rfc-azure-connection'  # Nom de votre service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Installer Terraform
      wget -O- https://www.hashicorp.com/terraform.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/terraform-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/terraform-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/terraform.list
      sudo apt-get update && sudo apt-get install terraform
      
      # Configuration Terraform
      cd $(Build.SourcesDirectory)/terraform
      
      # Initialiser avec backend Azure
      terraform init \
        -backend-config="storage_account_name=sarfcterraformstate" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=rfc-infra.tfstate" \
        -backend-config="resource_group_name=rg-rfc-infra-we"
      
      # Plan et Apply
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan